keys:
  - &admin_steffen age1uwr6528va47swxwclytpvlme36n2t5qf3c229da5nrhsupg8tyzqwyl60e
  - &server_oci age1vvf2d990pxrky3hl9um6kexvye6kp9rmcu626rx9q5htgnfurqdsduen2h
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *admin_steffen
          - *server_oci
