minio_user: ENC[AES256_GCM,data:dAUtodrzfvPiyw==,iv:glCmRjgmGxfM5zcHRdKprC9Rw3O5l9flDSdFA1E05VA=,tag:RzK6s2IGgM5qL92+CC5VgQ==,type:str]
minio_password: ENC[AES256_GCM,data:Fr0mbmZ3pHAQyIJGk2LNG+E6o05rA60S,iv:ROeZhTw7O5x4Gu22ePxYUs/P7dLaJrUYb2FdXwxIEtw=,tag:ctKt93MgitlX2RpWjg3WrQ==,type:str]
outline_s3_secret_key: ENC[AES256_GCM,data:THfJzXhDDpENuX+T5A1Zkdj7PpJvCk5valzkZXhUKk2fNdgBkXNf0w==,iv:wGSz7vMbfkGZ0MH+cPN52vhV4F+d/lKiq9/tHFXwi78=,tag:apJ6V8G0dLbSQvbJaU1v3Q==,type:str]
outline_auth0_secret_id: ENC[AES256_GCM,data:rCKuY923UR+ptU8tvqCKKX+syxSEvqGhZKYpolchhPqGNTP3zNcdPQxsJBZiqzH7RTjY8FUeJgl006f0fFi7ZQ==,iv:7KFzPcI5u4K5a3aOInjNI1+Dz2U8GtdilDDu633GDdI=,tag:qcIxQHm8kS+pgbY9vMM84A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uwr6528va47swxwclytpvlme36n2t5qf3c229da5nrhsupg8tyzqwyl60e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOUlVyY1ZxQUlhUTVVLzdZ
            TC8rOE5uenBhUHUyRG1DemJrUEg0a2dOTUJBCldvdmo0TXU3NU1PSHFFRmtBNFh5
            YytoVjdPRitZMW9CbHA4OTRYa3h1cU0KLS0tIG9jdDc1VmJIanFnOFJKREF1aXk3
            WnZhTXI2ZE1vbWI4SDVZTlFEdEN3OGsKTsSJGo2AwA9Z51u7/lo3InwKbbPdJ+QT
            tOh5j/kx2Hwpme66XrkxSUEvIyV8NZIbqedY8M/UkOQ3IUc3YjiWXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vvf2d990pxrky3hl9um6kexvye6kp9rmcu626rx9q5htgnfurqdsduen2h
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4M1VrUzV6NWJsQnljK1Q0
            cUpPL2k3SU5JRWM1MFVsWmFxTlJnbE9yV1hRCktxb0tYWCtTMU5sTUpyVGJjOVp6
            RkFEVmtQSU1aczd5SElaWTR6RElxZ3cKLS0tIHJob21Ec0FieHhUbnRtUUo1NWpx
            WE9wYmpvL1lRM0VvRnhWa01uUjlQcWsKNzziy8BKM57XiGwniSZvU5VsIVFPyPGE
            nxw9gszvt40P7YxccfJN/jqENU4ZCzUjmfudJalMU31zG4OvJw/7Vw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-09T11:33:07Z"
    mac: ENC[AES256_GCM,data:8WXaQwPZIswSWe8RH7kxhp1h8yCa0D7PPR4IMthltF1M4dHX8RC2Os2j5U9WFjct0czGGSX69GfEsbmyJHWCliOd8oqFE+WmyGiVjFvji/ZNRLGuSkM2ZzWKs5mvu1BD/jeO4CI7zFE12rEcCZFYwchtWsNJwaCRXowyrn7bJgQ=,iv:6zQyHT/sY9qjOg3F6v71rJePF+sGIZmsPpzq4OnwdUM=,tag:vE1VRJLVUHsX8QYl7MxviQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
