
name: Oracle CI
on:
  push:
    branches:
      - main
    paths:
      - 'lib/oracle-cloud/**/*.nix'
      - 'flake.lock'
  workflow_dispatch:

jobs:
  oracle:
    runs-on: ubuntu-latest
    concurrency: raspberryPi
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          diagnostic-endpoint: ""

      - uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3

      - uses: webfactory/ssh-agent@a6f90b1f127823b31d4d4a8d96047790581349bd # v0.9.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Build config
        run: |
          just remote @oracle
